name: calico
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - tensorboardx
  - tensorboard
  - pip
  - pip:
      - medmnist
      - netcal==1.3.4
      - matplotlib==3.5.3
